# Generated by Django 3.2.13 on 2022-07-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220702_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
    ]
