# Generated by Django 3.2.13 on 2022-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220620_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='paper_size',
            field=models.CharField(choices=[('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('DL', 'DL'), ('85x55', '85x55'), ('90x60', '90x60')], default='A4', max_length=5),
        ),
    ]
