# Generated by Django 3.2.13 on 2022-07-06 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_paper_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(200)]),
        ),
    ]
