# Generated by Django 3.2.13 on 2022-07-07 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(150)]),
        ),
    ]
