# Generated by Django 3.2.13 on 2022-06-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line1',
        ),
    ]
