# Generated by Django 3.2.13 on 2022-06-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_address_line1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_instance',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='', max_length=254),
        ),
    ]
