# Generated by Django 3.2.13 on 2022-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_artwork',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
