# Generated by Django 3.2.13 on 2022-07-04 21:01

import artwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='upload',
            field=models.FileField(upload_to=artwork.models.artwork_directory),
        ),
    ]
